//--------------------  COMMENTS --------------------------//

###
//Listar Opiniones
GET http://localhost:3330/api/comments

###
//Crear un Comentario
POST http://localhost:3330/api/comments/create
Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJ1c2VybmFtZSI6Ik1hdXJpY2lvIEFtZGluIiwiZXhwX2RhdGUiOjE2ODM3NDg1MDcsImlhdCI6MTY4Mzc0ODIwN30.a81fQ7vt_8mf1mirc4rflHrHb4bClnQ2IIWMuGwGU4Y

{
    "comentario": "Nuevo Compentario",
    "fecha_comentario": "",
    "estado": "Publicado",
    "usuario": "Carmen",
    "isDelete": 0,
    "curso": "",
    "curso_id": 21
}

###
//Editar un Comentario
POST http://localhost:3330/api/comments/update/7
Content-Type: application/json

{
    "comentario": "La mejor atención y el mejor precio",
    "estado": "Publicado",
    "usuario": "Mauricio",
    "isDelete": 0
}

###
//Ver único comentario
GET http://localhost:3330/api/comments/5

###
//Ver Opiniones por Curso
GET http://localhost:3330/api/comments/curso/5


###
//Eliminar un comentario
GET http://localhost:3330/api/comments/delete/6