//--------------------  CURSOS --------------------------//

###
//Listar Cursos
GET http://localhost:3330/api/courses

###
// Ver único curso
GET http://localhost:3330/api/courses/10

###
//Crear un curso
POST http://localhost:3330/api/courses/create 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJ1c2VybmFtZSI6Ik1hdXJpY2lvIEFtZGluIiwiaWF0IjoxNjgyNjI1MDg3LCJleHAiOjE2ODI2MjUzODd9.KZKnqxmNPDYTu9I-mOmxawhNje1qhVqmWVqBjWG_0n0

{
    "nombre": "WordPress Básico",
    "descripcion": null,
    "horario_inicio": null,
    "horario_cierre": null,
    "foto1": null,
    "foto2": null,
    "foto3": null,
    "precio": null,
    "estado": "inactivo",
    "isDelete": 1
}

###
// Editar un Curso
POST http://localhost:3330/api/courses/update/8
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJ1c2VybmFtZSI6Ik1hdXJpY2lvIEFtZGluIiwiZXhwX2RhdGUiOjE2ODI2OTIzMTMsImlhdCI6MTY4MjY4ODcxM30.ypLsK4UMLJAUlgmnL6fJmAb1LVfc82EWsxd8ZQXEaBY

{
    "nombre": "Joomla Avanzado",
    "descripcion": null,
    "horario_inicio": null,
    "horario_cierre": null,
    "foto1": null,
    "foto2": null,
    "foto3": null,
    "precio": null,
    "estado": "inactivo",
    "isDelete": 1
}

###
//Eliminar un curso por Id
GET http://localhost:3330/api/courses/delete/6
