//--------------------  CURSOS --------------------------//

###
//Listar Cursos
GET http://localhost:3330/api/courses

###
//Listar Últimos 10 Cursos
GET http://localhost:3330/api/courses/lastcourses


###
//Cursos para el Buscador
GET http://localhost:3330/api/courses/search

###
// Ver único curso
GET http://localhost:3330/api/courses/course/23

###
//Ver por Categoría
GET http://localhost:3330/api/courses/arte

###
//Crear un curso
POST http://localhost:3330/api/courses/create 
Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJ1c2VybmFtZSI6Ik1hdXJpY2lvIEFtZGluIiwiZXhwX2RhdGUiOjE2ODU2NDkyODUsImlhdCI6MTY4NTY0ODk4NX0.PF_lT04iqxF4JhxM0S1cGdqBfX6BxjCAJBtih4msbYM

{
    "nombre": "Otro Curso",
    "descripcion": "",
    "ciudad": "",
    "fecha_inicio": "",
    "fecha_fin": "",
    "precio": 100,
    "horario": "Mañana",
    "total_horas": 3,
    "estado": "inactivo",
    "isDelete": 1,
    "rating": 4,
    "categoria": "Informática"
}

###
// Editar un Curso
POST http://localhost:3330/api/courses/update/8
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJ1c2VybmFtZSI6Ik1hdXJpY2lvIEFtZGluIiwiZXhwX2RhdGUiOjE2ODI2OTIzMTMsImlhdCI6MTY4MjY4ODcxM30.ypLsK4UMLJAUlgmnL6fJmAb1LVfc82EWsxd8ZQXEaBY

{
    "nombre": "Joomla Avanzado",
    "descripcion": null,
    "horario_inicio": null,
    "horario_cierre": null,
    "foto1": null,
    "foto2": null,
    "foto3": null,
    "precio": null,
    "estado": "inactivo",
    "isDelete": 1
}

###
//Eliminar un curso por Id
GET http://localhost:3330/api/courses/delete/6
