//--------------------  USUARIOS --------------------------//

###
//Listar usuarios
GET http://localhost:3330/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJ1c2VybmFtZSI6Ik1hdXJpY2lvIEFtZGluIiwiZXhwX2RhdGUiOjE2ODY2ODkwNzAsInJvbGwiOiJhZG1pbiIsImlhdCI6MTY4NjY4ODc3MH0.CMLvCvmKvqg7_pA19xFcIIZT0yAwl5kEKKtYii13XL4

### //Ver único usuario
GET http://localhost:3330/api/users/63
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJ1c2VybmFtZSI6Ik1hdXJpY2lvIEFtZGluIiwiZXhwX2RhdGUiOjE2ODI2OTIzMTMsImlhdCI6MTY4MjY4ODcxM30.ypLsK4UMLJAUlgmnL6fJmAb1LVfc82EWsxd8ZQXEaBY

### Buscar curso por palabra
GET http://localhost:3330/api/courses/search/guitarra

# TODO
### //Crear un usuario
POST http://localhost:3330/api/users/create
Content-Type: application/json

{
    "name": "Emma",
    "lastname": "Requena",
    "ciudad": "Madrid",
    "picture": "",
    "email": "emma@gmail.com",
    "password": "emma",
    "roll": "cliente",
    "isDelete": 0
}

###
//Editar Usuario
PUT http://localhost:3330/api/users/update/84
Content-Type: application/json

{
    "name": "Eva",
    "lastname": "Ruiz Spencer",
    "ciudad": "Barcelona",
    "picture": null,
    "email": "evix@gmail.com",
    "password": "evix",
    "roll": "cliente",
    "isDelete": 0
}

###
//Elminar un usuario por Id
GET http://localhost:3330/api/users/delete/13


###
//Registro de un usuario
POST http://localhost:3330/api/users/register
Content-Type: application/json

{
    "name": "Rosa Esteban",
    "lastname": "Castro",
    "ciudad": "Madrid",
    "picture": null,
    "email": "rosacastro@gmail.com",
    "password": "123456789",
    "roll": "admin",
    "isDelete": 0
}

###
//Login
POST http://localhost:3330/api/users/login
Content-Type: application/json

{
    "email": "maomur@gmail.com",
    "password": "maomur"
}
